In [59]:
from deepface import DeepFace
import numpy as np
import cv2

In [60]:
embedding_objs = DeepFace.represent(
  img_path = "/Users/naveenpoliasetty/Downloads/David2.0/david2.0/Frames/frame_1.jpg"
)
face_embeddings = [embedding_objs[x]['embedding'] for x in range(len(embedding_objs))]

In [61]:
embds = DeepFace.represent('/Users/naveenpoliasetty/Downloads/David2.0/david2.0/faces/213J1A42C9.jpg')
embeddings = [embds[x]['embedding'] for x in range(len(embds))]

In [62]:
embeddings

[[0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.010544121339454942,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.03131506033492277,
  0.005449136886994259,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.008463950856095848,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.03551032632575894,
  0.0,
  0.0,
  0.0,
  0.0,
  0.17186219255242288,
  0.0,
  0.011928850728427937,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.013089612135590685,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.05317124341907937,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.021446872468431098,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0391

In [57]:
def cosine_similarity(vec1, vec2):
    dot_product = np.dot(vec1, vec2)

    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)
    
    if norm_vec1 == 0 or norm_vec2 == 0:
        return 0.0
    cosine_sim = dot_product / (norm_vec1 * norm_vec2)
    
    return cosine_sim

def compare_faces(embedd1, indiviual_faces_embeddings):
    scores, dot_scores = [], []
    for x in embedd1:
        scores.append(cosine_similarity(indiviual_faces_embeddings, x))
        dot_scores.append(np.dot(indiviual_faces_embeddings, x))


    for x, y in zip(scores, dot_scores):
        if x > 0.5:
            print('True cosine similarity')
     
        if y > 0.5:
            print('True dot product')
    return np.argmax(scores), np.argmax(dot_scores), scores, dot_scores


In [58]:
compare_faces(face_embeddings, embeddings)

(1,
 1,
 [array([0.08477628]),
  array([0.46236115]),
  array([0.08604451]),
  array([0.14955365])],
 [array([0.08477628]),
  array([0.46236115]),
  array([0.08604451]),
  array([0.14955365])])

In [ ]:
(3,
 3,
 [array([0.12032847]),
  array([0.13189688]),
  array([0.10653398]),
  array([0.61274976])],
 [array([0.12032847]),
  array([0.13189688]),
  array([0.10653398]),
  array([0.61274976])])